### ISSUE TITLE
Can't import this package on the last release only

### ISSUE THREAD

**Issue by macabeus** [dubzzz/fast-check#543]
## 🐛 Bug Report

I was trying to import this module on my test file, but I can't.
So I tried to downgrade from the version `1.22.0` to `1.20.1`, and now everything is working ✨

```
➜  common git:(chore/add-tests) ✗ yarn jest
yarn run v1.21.1
$ /Users/macabeus/ApenasMeu/project/front/common/node_modules/.bin/jest
 FAIL  tests/validate.test.ts
  ● Test suite failed to run

    Cannot find module 'fast-check' from 'validate.test.ts'

    > 1 | const fc = require('fast-check')
        |            ^
      2 | import * as validates from '../src/validate'
      3 | 
      4 | test('isEmpty should return true for an empty string', () => {

      at Resolver.resolveModule (../node_modules/jest-resolve/build/index.js:276:11)
      at Object.<anonymous> (tests/validate.test.ts:1:12)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.451s, estimated 3s
Ran all test suites.
```

## Your environment

| Packages / Softwares  | Version(s) |
| --------------------- | ---------- |
| node                  |  v13.5.0          |
| TypeScript           |   3.7.2         |

**Comment by sandersn** [comment]
I think the most recent version is missing the build. There is no lib folder here: https://unpkg.com/browse/fast-check@1.22.0/

**Comment by dubzzz** [comment]
Sorry for the inconvenience, I'll try to find a way to fix it asap. Thanks for the report

**Comment by dubzzz** [comment]
@macabeus @sandersn 
Thanks a lot for the report. It should be fixed with 1.22.1.

See https://unpkg.com/browse/fast-check@1.22.1/

Can you confirm everything works fine now?

**Comment by macabeus** [comment]
@dubzzz Thank you. Now everything is working on `1.22.1` version 😄
